name: Java Kadai10th CI

on:
  push:
    branch: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Boot Docker
        run: docker compose up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant Permission
        run: chmod +x ./gradlew

      - name: Conduct Tests
        run: ./gradlew test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test content
          path: build/reports/
